name: Create Azure resources
on: [workflow_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: create resources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ vars.AZURE_RG }}
          template: ${{ github.workspace }}/config/main.bicep
          parameters: 'namePrefix=${{ vars.AZURE_PREFIX }}'
          failOnStdErr: false